version: "3"

services: 
  node-app:
    build:
      context: .
      args: 
        - NODE_ENV=development
    ports: 
      - "3000:3000"
    volumes: 
      - ./src:/usr/local/app
      - exclude:/usr/local/app/node_modules
    command: npm run dev
    
volumes:
  exclude: