version: "3"

services: 
  node-app:
    build: .
    volumes: 
      - ./src:/usr/local/app
      - exclude:/usr/local/app/node_modules
    env_file: 
      - ./.env
    depends_on: 
      - "mongo"
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db 
    env_file: 
      - ./.env
volumes: 
  exclude:
  mongo:
networks: 
  default:
    name: internal 
  