GET http://localhost:3000/entries HTTP/1.1

###

POST http://localhost:3000/entries HTTP/1.1
Content-Type: application/json

{
  "content": "this is content"
}

###

# Use ID from POST request above in below requests

PUT http://localhost:3000/entries/60f767c9ca401700ab193647 HTTP/1/1
Content-Type: application/json

{
  "content": "new content"
}

###

PATCH http://localhost:3000/entries/60f767c9ca401700ab193647 HTTP/1/1
Content-Type: application/json

{
  "content": "newer content"
}

###

DELETE http://localhost:3000/entries/60f76bfbc0010a00d5b34650 HTTP/1/1

###

POST http://localhost:3000/users/signup HTTP/1.1
Content-Type: application/json

{
  "username": "foomanchubar",
  "password": "thisisahashpass!"
}

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "username": "foomanchubar",
  "password": "thisisahashpass!"
}
